export const SHOW_LOADER_START = 'ui/SHOW_LOADER_START';
export const SHOW_LOADER_SUCCESS = 'ui/SHOW_LOADER_SUCCESS';
export const SHOW_LOADER_ERROR = 'ui/SHOW_LOADER_ERROR';

export const HIDE_LOADER_START = 'ui/HIDE_LOADER_START';
export const HIDE_LOADER_SUCCESS = 'ui/HIDE_LOADER_SUCCESS';
export const HIDE_LOADER_ERROR = 'ui/HIDE_LOADER_ERROR';
